defaults: &defaults
  docker:
    - image: gradle:4.3-jdk8
      environment:
        BUILDENV: dev

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: ./gradlew clean jpi
      - store_artifacts:
          path: ~/build/libs
