defaults: &defaults
  docker:
    - image: gradle:4.3-jdk8
      environment:
        BUILDENV: dev

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: ls -la
      - run: pwd
      - run: ./gradlew clean jpi

